name: release

on:
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run typechain
      - if: github.event.release.prerelease == true
        run: npm run build-dev
        env:
          REACT_APP_IS_INVEST: false
          REACT_APP_IS_COLLATERAL: true
          NODE_ENV: development
          REACT_APP_DEFAULT_CHAIN_ID: 3
          REACT_APP_UNISENDER_API: ${{secrets.REACT_APP_UNISENDER_API}}
          INFURA_API_KEY: ${{secrets.REACT_APP_INFURA_API_KEY}}
          REACT_APP_PORTIS_ID: ${{secrets.REACT_APP_PORTIS_ID}}
          REACT_APP_FORTMATIC_KEY: ${{secrets.REACT_APP_FORTMATIC_KEY_TEST}}
          REACT_APP_SENTRY: ${{secrets.REACT_APP_SENTRY}}
          REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}
          REACT_APP_TREZOR_URL: ${{secrets.REACT_APP_TREZOR_URL}}
          REACT_APP_TREZOR_EMAIL: ${{secrets.REACT_APP_TREZOR_EMAIL}}
          REACT_APP_PANCAKESWAP_URL: https://app.1inch.io/#/56/swap
          REACT_APP_SWOP_FI_ENABLE: true
          REACT_APP_WAVES_URL: https://waves.exchange
          REACT_APP_SWOP_URL: https://swop.fi/exchange/3PAgYAV4jYJ7BF8LCVNU9tyWCBtQaqeLQH4?utm_source=bondappetit&utm_medium=partner&utm_campaign=buy_bag
          REACT_APP_BUY_BACK_ENABLE: false
      - if: github.event.release.prerelease == false
        run: npm run build
        env:
          REACT_APP_IS_INVEST: false
          REACT_APP_IS_COLLATERAL: false
          REACT_APP_DEFAULT_CHAIN_ID: 1
          REACT_APP_UNISENDER_API: ${{secrets.REACT_APP_UNISENDER_API}}
          INFURA_API_KEY: ${{secrets.REACT_APP_INFURA_API_KEY}}
          REACT_APP_PORTIS_ID: ${{secrets.REACT_APP_PORTIS_ID}}
          REACT_APP_FORTMATIC_KEY: ${{secrets.REACT_APP_FORTMATIC_KEY_PRODUCTION}}
          REACT_APP_SENTRY: ${{secrets.REACT_APP_SENTRY}}
          REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}
          REACT_APP_TREZOR_URL: ${{secrets.REACT_APP_TREZOR_URL}}
          REACT_APP_TREZOR_EMAIL: ${{secrets.REACT_APP_TREZOR_EMAIL}}
          REACT_APP_PANCAKESWAP_URL: https://app.1inch.io/#/56/swap
          REACT_APP_SWOP_FI_ENABLE: true
          REACT_APP_WAVES_URL: https://waves.exchange
          REACT_APP_SWOP_URL: https://swop.fi/exchange/3PAgYAV4jYJ7BF8LCVNU9tyWCBtQaqeLQH4?utm_source=bondappetit&utm_medium=partner&utm_campaign=buy_bag
          REACT_APP_BUY_BACK_ENABLE: false
          REACT_APP_IMPROPERLY_PROPOSALS: 15,13,10,7
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-release
          path: |
            build

  publish:
    needs: build-and-test
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Download build-release
        uses: actions/download-artifact@v2
        with:
          name: build-release
          path: ./build

      - name: Publish dev
        if: github.event.release.prerelease == true
        run: |
          cp -rf $GITHUB_WORKSPACE ~/$GITHUB_REPOSITORY-dev.new
          mv ~/$GITHUB_REPOSITORY-dev ~/$GITHUB_REPOSITORY-dev.old
          mv ~/$GITHUB_REPOSITORY-dev.new ~/$GITHUB_REPOSITORY-dev
          rm -rf ~/$GITHUB_REPOSITORY-dev.old

      - name: Publish stable
        if: github.event.release.prerelease == false
        run: |
          cp -rf $GITHUB_WORKSPACE ~/$GITHUB_REPOSITORY.new
          mv ~/$GITHUB_REPOSITORY ~/$GITHUB_REPOSITORY.old
          mv ~/$GITHUB_REPOSITORY.new ~/$GITHUB_REPOSITORY
          rm -rf ~/$GITHUB_REPOSITORY.old

  cloudflare-purge:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Purge cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
